name: API Issue
description: Use this template for API-related issues.
title: "[API] "
labels: ["TODO"]
assignees: ""

body:
  - type: markdown
    attributes:
      value: |
        Please provide the details of the API issue below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the issue.
      placeholder: Describe the issue here...