name: Note doc string
description: Improvements to docstrings from curated notes
title: "[doc-string]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an improvement!
  - type: input
    id: name
    attributes:
      label: Name of result
      description: What is the name of the result you are suggesting an improvement for?
      placeholder:
    validations:
      required: true
  - type: textarea
    id: improvement
    attributes:
      label: Improvement
      description: What is the improvement you are suggesting?
      placeholder:
    validations:
      required: true
