name: PR Comment

on:
  pull_request_target:
    types: 
      - opened

jobs:
    build:
        name: Comment a pull_request
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
  
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Comment a pull_request
              uses: mb2dev/github-action-comment-pull-request@1.0.0
              with:
                message: "Hello, Thank you for this PR!"
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}